#region usings

using System.Collections.Generic;
using System.Linq;
using System.Threading;

using Framework.Annotations;
using Framework.Extensions;

using Preferences.Interfaces;

#endregion

namespace Preferences.DomainModels
{

    /// <summary>
    ///     Class PreferencesModel.
    /// </summary>
    /// <seealso cref="Preferences.Interfaces.IPreferencesModel" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for PreferencesModel
    public class PreferencesModel : IPreferencesModel
    {

        #region instance non-public fields

        /// <summary>
        ///     The by identifier
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for _byId
        [ NotNull ]
        private readonly IDictionary < int, IPersonColorPreferenceModel > _byId;

        /// <summary>
        ///     The records added
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for _recordsAdded
        private int _recordsAdded;

        #endregion

        #region public constructors

        /// <summary>
        ///     Initializes a new instance of the <see cref="PreferencesModel" /> class.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public PreferencesModel ( )
        {
            _byId = new Dictionary < int, IPersonColorPreferenceModel > ( );
        }

        #endregion

        #region instance public methods

        /// <summary>
        ///     Adds the specified modifiable.
        /// </summary>
        /// <param name="modifiable">The modifiable.</param>
        /// <returns>IPersonColorPreferenceModel.</returns>
        /// <inheritdoc />
        public int Add ( IPersonColorPreferenceModel modifiable )
        {
            var copy = new PersonColorPreferenceModel ( modifiable );
            var newId = Interlocked.Increment ( ref _recordsAdded );
            copy.Id = newId;

            _byId [ newId ] = copy;

            return newId;
        }

        /// <summary>
        ///     Adds the specified line.
        /// </summary>
        /// <param name="line">The line.</param>
        /// <param name="delimiter">The delimiter.</param>
        /// <returns>System.Int32.</returns>
        /// <inheritdoc />
        public int Add ( string line, char delimiter )
        {
            var record = PreferencesHelpers.Parse ( line, delimiter );

            var result = Add ( record );

            return result;
        }

        /// <summary>
        ///     Adds the specified line.
        /// </summary>
        /// <param name="line">The line.</param>
        /// <returns>System.Int32.</returns>
        /// <inheritdoc />
        public int Add ( string line )
        {
            var delimiter = PreferencesHelpers.DecideDelimiterFromLine ( line );
            var result = Add ( line, delimiter );

            return result;
        }

        /// <summary>
        ///     Adds the specified modifiable.
        /// </summary>
        /// <param name="modifiable">The modifiable.</param>
        /// <inheritdoc />
        public void Add ( IEnumerable < IPersonColorPreferenceModel > modifiable )
        {
            var personColorPreferenceModels = modifiable.ToSafeList ( );
            personColorPreferenceModels.ForEach ( r => Add ( r ) );
        }

        /// <summary>
        ///     Adds the specified lines.
        /// </summary>
        /// <param name="lines">The lines.</param>
        /// <param name="delimiter">The delimiter.</param>
        /// <inheritdoc />
        public void Add ( IEnumerable < string > lines, char delimiter )
        {
            foreach ( var line in lines )
            {
                Add ( line, delimiter );
            }
        }

        /// <summary>
        ///     Bies the birth date.
        /// </summary>
        /// <returns>IEnumerable&lt;IPersonColorPreferenceModel&gt;.</returns>
        /// <inheritdoc />
        public IEnumerable < IPersonColorPreferenceModel > ByBirthDate ( )
        {
            var personColorPreferenceModels = _byId.Values.ToSafeList ( );
            var result = personColorPreferenceModels.OrderBy ( s => s.DateTimeBirth ).ToList ( );

            return result;
        }

        /// <summary>
        ///     Bies the last name of the gender.
        /// </summary>
        /// <returns>IEnumerable&lt;IPersonColorPreferenceModel&gt;.</returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ByGenderLastName
        public IEnumerable < IPersonColorPreferenceModel > ByGenderLastName ( )
        {
            var personColorPreferenceModels = _byId.Values.ToSafeList ( );
            var result = personColorPreferenceModels.OrderBy ( r => r.Gender ).ThenBy ( r => r.LastNameUpper ).ToList ( );

            return result;
        }

        /// <summary>
        ///     Bies the last name descending.
        /// </summary>
        /// <returns>IEnumerable&lt;IPersonColorPreferenceModel&gt;.</returns>
        /// <inheritdoc />
        public IEnumerable < IPersonColorPreferenceModel > ByLastNameDescending ( )
        {
            var personColorPreferenceModels = _byId.Values.ToSafeList ( );
            var result = personColorPreferenceModels.OrderByDescending ( r => r.LastNameUpper ).ToList ( );

            return result;
        }

        /// <summary>
        ///     Bies the name.
        /// </summary>
        /// <returns>IEnumerable&lt;IPersonColorPreferenceModel&gt;.</returns>
        /// <inheritdoc />
        public IEnumerable < IPersonColorPreferenceModel > ByName ( )
        {
            var personColorPreferenceModels = _byId.Values.ToSafeList ( );
            var result = personColorPreferenceModels.OrderBy ( r => r.LastNameUpper ).ThenBy ( r => r.FirstNameUpper ).ToList ( );

            return result;
        }

        /// <summary>
        ///     Returns a <see cref="System.String" /> that represents this instance.
        /// </summary>
        /// <returns>A <see cref="System.String" /> that represents this instance.</returns>
        /// <inheritdoc />
        public override string ToString ( )
        {
            return _byId.Count + " entries";
        }

        #endregion

        #region instance public properties and indexers

        /// <summary>
        ///     Gets the preferences.
        /// </summary>
        /// <value>The preferences.</value>
        /// <inheritdoc />
        public IEnumerable < IPersonColorPreferenceModel > PersonColorPreferences
        {
            get
            {
                return _byId.Values.ToList ( );
            }
        }

        /// <summary>
        ///     Gets the records added.
        /// </summary>
        /// <value>The records added.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for RecordsAdded
        public int RecordsAdded
        {
            get
            {
                return _recordsAdded;
            }
        }

        #endregion

    }

}
