#region usings

using System.Web.Mvc;

using Framework.Annotations;

#endregion

namespace Preferences.WebSite
{

    /// <summary>
    ///     Class FilterConfig.
    /// </summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for FilterConfig
    public class FilterConfig
    {

        #region class public methods

        /// <summary>
        ///     Registers the global filters.
        /// </summary>
        /// <param name="filters">The filters.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for RegisterGlobalFilters
        public static void RegisterGlobalFilters ( [ NotNull ] GlobalFilterCollection filters )
        {
            filters.Add ( new HandleErrorAttribute ( ) );
        }

        #endregion

    }

}
