#region usings

using System.Web.Http;

using Framework.Annotations;

#endregion

namespace Preferences.WebSite
{

    /// <summary>
    ///     Class WebApiConfig.
    /// </summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for WebApiConfig
    public static class WebApiConfig
    {

        #region class public methods

        /// <summary>
        ///     Registers the specified configuration.
        /// </summary>
        /// <param name="config">The configuration.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Register
        public static void Register ( [ NotNull ] HttpConfiguration config )
        {
            // Web API configuration and services

            // Web API routes
            config.MapHttpAttributeRoutes ( );

            config.Routes.MapHttpRoute ( "DefaultApi",
                "{controller}",
                new
                {
                    id = RouteParameter.Optional
                } );
        }

        #endregion

    }

}
