#region usings

using System;
using System.Collections.Generic;
using System.Linq;

using Framework.Extensions;

using Xunit;

#endregion

namespace Framework.UnitTests
{

    /// <summary>
    ///     Class LinqExtensionsUnitTests. This class cannot be inherited.
    /// </summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for LinqExtensionsUnitTests
    public static class LinqExtensionsUnitTests
    {

        #region class public methods

        /// <summary>
        ///     Tests for each enumerable extension.
        /// </summary>
        [ Fact ]
        public static void Test_forEach_enumerable_extension ( )
        {
            var random = new Random ( );
            var list = Enumerable.Range ( 0, 100 ).Select ( i => random.Next ( 1, 1000 ) ).ToList ( );

            // List does have a ForEach defined, so we use Sum here
            var sum1 = list.Sum ( i => i );

            var sum2 = 0;
            var asEnumerable = ( IEnumerable < int > ) list;
            asEnumerable.ForEach ( i => sum2 += i );

            Assert.Equal ( sum1, sum2 );
        }

        #endregion

    }

}
