#region usings

using System;

using Framework.Annotations;

#endregion

namespace Preferences.Interfaces
{

    /// <summary>
    ///     Interface IPersonColorPreferenceModel
    /// </summary>
    /// <remarks>
    ///     For now, there is no validation (syntax) or verification (range of values) being done.
    ///     <see cref="string" /> properties that are often used for sorting have an upper invariant
    ///     copy of the data, which makes for faster ordering.
    /// </remarks>
    public interface IPersonColorPreferenceModel
    {

        #region instance public methods

        /// <summary>
        ///     Populates from.
        /// </summary>
        /// <param name="source">The source.</param>
        void PopulateFrom ( [ NotNull ] IPersonColorPreferenceModel source );

        #endregion

        #region instance public properties and indexers

        /// <summary>
        ///     Gets or sets the date of birth.
        /// </summary>
        /// <value>The date of birth.</value>
        [ NotNull ]
        string DateOfBirth
        {
            get;
            set;
        }

        /// <summary>
        ///     Gets or sets the date time birth.
        /// </summary>
        /// <value>The date time birth.</value>
        /// <remarks>
        ///     This is a calculated value, and should be set whenever <see cref="DateOfBirth" /> changes.
        /// </remarks>
        DateTime DateTimeBirth
        {
            get;
        }

        /// <summary>
        ///     Gets or sets the color of the favorite.
        /// </summary>
        /// <value>The color of the favorite.</value>
        [ NotNull ]
        string FavoriteColor
        {
            get;
            set;
        }

        /// <summary>
        ///     Gets or sets the first name.
        /// </summary>
        /// <value>The first name.</value>
        [ NotNull ]
        string FirstName
        {
            get;
            set;
        }

        /// <summary>
        ///     Gets the first name upper.
        /// </summary>
        /// <value>The first name upper.</value>
        /// <remarks>
        ///     This is a calculated value, and should be set whenever <see cref="FirstName" /> changes.
        /// </remarks>
        [ NotNull ]
        string FirstNameUpper
        {
            get;
        }

        /// <summary>
        ///     Gets or sets the gender.
        /// </summary>
        /// <value>The gender.</value>
        [ NotNull ]
        string Gender
        {
            get;
            set;
        }

        /// <summary>
        ///     Gets or sets the identifier.
        /// </summary>
        /// <value>The identifier.</value>
        /// <remarks>
        ///     This is an internal value maintained by the data provider,
        ///     such as <see cref="IPreferencesModel" />
        /// </remarks>
        int Id
        {
            get;
            set;
        }

        /// <summary>
        ///     Gets or sets the last name.
        /// </summary>
        /// <value>The last name.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for LastName
        [ NotNull ]
        string LastName
        {
            get;
            set;
        }

        /// <summary>
        ///     Gets the last name upper.
        /// </summary>
        /// <value>The last name upper.</value>
        /// <remarks>
        ///     This is a calculated value, and should be set whenever <see cref="LastName" /> changes.
        /// </remarks>
        [ NotNull ]
        string LastNameUpper
        {
            get;
        }

        #endregion

    }

}
