#region usings

using System.Collections.Generic;

using Framework.Annotations;

#endregion

namespace Preferences.Interfaces
{

    /// <summary>
    ///     Interface IPreferencesModel
    /// </summary>
    public interface IPreferencesModel
    {

        #region instance public methods

        /// <summary>
        ///     Adds the specified modifiable.
        /// </summary>
        /// <param name="modifiable">The modifiable.</param>
        /// <returns>IPersonColorPreferenceModel.</returns>
        int Add ( [ NotNull ] IPersonColorPreferenceModel modifiable );

        /// <summary>
        ///     Adds the specified lines.
        /// </summary>
        /// <param name="lines">The lines.</param>
        /// <param name="delimiter">The delimiter.</param>
        void Add ( [ NotNull ] [ ItemNotNull ] IEnumerable < string > lines, char delimiter );

        /// <summary>
        ///     Adds the specified lines.
        /// </summary>
        /// <param name="records">The records.</param>
        void Add ( [ NotNull ] [ ItemNotNull ] IEnumerable < IPersonColorPreferenceModel > records );

        /// <summary>
        ///     Adds the specified line.
        /// </summary>
        /// <param name="line">The line.</param>
        /// <param name="delimiter">The delimiter.</param>
        /// <returns></returns>
        int Add ( [ NotNull ] string line, char delimiter );

        /// <summary>
        ///     Adds the specified line.
        /// </summary>
        /// <param name="line">The line.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Add
        int Add ( [ NotNull ] string line );

        /// <summary>
        ///     Bies the birth date.
        /// </summary>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ByBirthDate
        [ NotNull ]
        [ ItemNotNull ]
        IEnumerable < IPersonColorPreferenceModel > ByBirthDate ( );

        /// <summary>
        ///     Bies the last name of the gender.
        /// </summary>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ByGenderLastName
        [ NotNull ]
        [ ItemNotNull ]
        IEnumerable < IPersonColorPreferenceModel > ByGenderLastName ( );

        /// <summary>
        ///     Bies the last name descending.
        /// </summary>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ByLastNameDescending
        [ NotNull ]
        [ ItemNotNull ]
        IEnumerable < IPersonColorPreferenceModel > ByLastNameDescending ( );

        /// <summary>
        ///     Bies the name.
        /// </summary>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for ByName
        [ NotNull ]
        [ ItemNotNull ]
        IEnumerable < IPersonColorPreferenceModel > ByName ( );

        #endregion

        #region instance public properties and indexers

        /// <summary>
        ///     Gets the preferences.
        /// </summary>
        /// <value>The preferences.</value>
        [ NotNull ]
        [ ItemNotNull ]
        IEnumerable < IPersonColorPreferenceModel > PersonColorPreferences
        {
            get;
        }

        #endregion

    }

}
