#region usings

using System;
using System.Threading.Tasks;

using Preferences.Extensions;

using Xunit;

#endregion

namespace Preferences.UnitTests
{

    /// <summary>
    /// Class DateExtensionsUnitTests. This class cannot be inherited.
    /// </summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for DateExtensionsUnitTests
    public sealed class DateExtensionsUnitTests
    {

        #region instance public methods

        /// <summary>
        /// Bads the leap.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for BadLeap
        [Fact ]
        public void BadLeap ( )
        {
            var exception = Record.Exception ( ( ) => "2/29/2017".FromPreferenceFormat ( ) );
            Assert.NotNull ( exception );
            Assert.IsType < FormatException > ( exception );
        }

        /// <summary>
        /// Days the missing.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DayMissing
        [Fact ]
        public void DayMissing ( )
        {
            var exception = Record.Exception ( ( ) => "1//2017".FromPreferenceFormat ( ) );
            Assert.NotNull ( exception );
            Assert.IsType < FormatException > ( exception );
        }

        /// <summary>
        /// Days the month order.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DayMonthOrder
        [Fact ]
        public void DayMonthOrder ( )
        {
            var exception = Record.Exception ( ( ) => "31/1/2017".FromPreferenceFormat ( ) );
            Assert.NotNull ( exception );
            Assert.IsType < FormatException > ( exception );
        }

        /// <summary>
        /// Monthes the blank.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for MonthBlank
        [Fact ]
        public void MonthBlank ( )
        {
            var exception = Record.Exception ( ( ) => "31/ 1/2017".FromPreferenceFormat ( ) );
            Assert.NotNull ( exception );
            Assert.IsType < FormatException > ( exception );
        }

        /// <summary>
        /// Monthes the left0.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for MonthLeft0
        [Fact ]
        public void MonthLeft0 ( )
        {
            var exception = Record.Exception ( ( ) => "31/001/2017".FromPreferenceFormat ( ) );
            Assert.NotNull ( exception );
            Assert.IsType < FormatException > ( exception );
        }

        /// <summary>
        /// Rounds the trip.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for RoundTrip
        [Fact ]
        public void RoundTrip ( )
        {
            var epoch = new DateTime ( 1800, 1, 1 );

            Parallel.For ( 0,
                300 * 366,
                day =>
                {
                    var target = epoch.AddDays ( day );
                    var asString1 = target.ToPreferenceFormat ( );
                    var asDateTime = asString1.FromPreferenceFormat ( );
                    var asString2 = asDateTime.ToPreferenceFormat ( );

                    Assert.Equal ( target, asDateTime );

                    Assert.Equal ( asString1, asString2 );

                    Assert.Equal ( target, target.ToPreferenceFormat ( ).FromPreferenceFormat ( ) );
                } );
        }

        /// <summary>
        /// Years the format.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for YearFormat
        [Fact ]
        public void YearFormat ( )
        {
            var exception = Record.Exception ( ( ) => "1/1/17".FromPreferenceFormat ( ) );
            Assert.NotNull ( exception );
            Assert.IsType < FormatException > ( exception );
        }

        #endregion

    }

}
