using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Preferences.UnitTests
{
    /// <summary>
    /// Class DomainModelsUnitTests.
    /// </summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for DomainModelsUnitTests
    public static class DomainModelsUnitTests
    {

    }
}
