#region usings

using System.Web;
using System.Web.Http;

#endregion

namespace Records.WebService
{

    /// <summary>
    ///     Class WebApiApplication.
    /// </summary>
    /// <seealso cref="System.Web.HttpApplication" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for WebApiApplication
    public class WebApiApplication : HttpApplication
    {

        #region instance non-public methods

        /// <summary>
        ///     Applications the start.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Application_Start
        protected void Application_Start ( )
        {
            GlobalConfiguration.Configure ( WebApiConfig.Register );
        }

        #endregion

    }

}
