#region usings

using System.Web.Http;

#endregion

namespace Records.WebService
{

    /// <summary>
    ///     Class WebApiConfig.
    /// </summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for WebApiConfig
    public static class WebApiConfig
    {

        #region class public methods

        /// <summary>
        ///     Registers the specified configuration.
        /// </summary>
        /// <param name="config">The configuration.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Register
        public static void Register ( HttpConfiguration config )
        {
            config.MapHttpAttributeRoutes ( );

            config.Routes.MapHttpRoute ( "DefaultApi",
                "{controller}",
                new
                {
                    id = RouteParameter.Optional
                } );
        }

        #endregion

    }

}
