#region usings

using System.Web.Mvc;

using Preferences.WebSite.Controllers;

using Xunit;

#endregion

namespace Preferences.WebSite.UnitTests.Controllers
{

    /// <summary>
    ///     Class HomeControllerTest.
    /// </summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for HomeControllerTest
    public class HomeControllerTest
    {

        #region instance public methods

        /// <summary>
        ///     Indexes this instance.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Index
        [ Fact ]
        public void Index ( )
        {
            // Arrange
            var controller = new HomeController ( );

            // Act
            var result = controller.Index ( ) as ViewResult;

            // Assert
            Assert.NotNull ( result );
            Assert.Equal ( "Home Page", result.ViewBag.Title );
        }

        #endregion

    }

}
